### ISSUE TITLE
Pause Day Cycle making day cycle not continue after a player is online

### ISSUE THREAD

**Issue by BitSents** [clo4/datapacks#24]
I'm running the most recent version, with detect afk players and afk sleep also installed. Any idea what could be causing this? the time does not move forward at all

**Comment by clo4** [comment]
Oh that's super weird! That's one of the things that I specifically tested to make sure it was working. Just tested again to confirm, and with exactly those datapacks installed it works fine for me.

Need some more info:
- Do all players online have the `afk` tag? `/tag @a list`
- Are there any other data packs installed, and what are they?
- What game version are you running?
- If you're an admin (I'm assuming you are?) can you run the following commands and send the output:
  - `/scoreboard players get #do_daylight_cycle pause_daylight_cycle.dummy`
  - `/scoreboard players get #is_paused pause_daylight_cycle.dummy`
- Is there anything else that might be relevant?

I *truly* don't know how this could have broken because the only thing that changed was the name of the folders, there literally wasn't a change in the logic at all haha.

My only guess is that while the daylight cycle was paused, somehow the scoreboard that it uses to keep track of *how* it was paused got reset, so it thought a player had disabled the daylight cycle and didn't resume it. That's what I'm trying to find out with those scoreboard values.

After you've given me the result of those commands, I think this will fix it:
```
/function pause_day_cycle:uninstall
/gamerule doDaylightCycle true
/reload
```

But if it breaks after that, I'll have to keep digging to figure out what the problem is. I even tested both cases of upgrading the world from 1.20.x to 1.21 while the daylight cycle is and isn't paused.

**Comment by clo4** [comment]
Oh one more thing actually. Because datapacks are world based I can actually do this debugging myself if you're willing to send me the world file - I'm @clo4 on Discord if you want to DM it to me.

**Comment by BitSents** [comment]
i was able to patch it just by turning on the gamerule back on and it worked perfectly even when no players are online. not sure why it was paused to start with upon world launch. not sure why but it's fixed now and works as intended.

**Comment by clo4** [comment]
Extremely strange. I’ll keep a lookout for that on my own worlds too. Thanks for letting me know, appreciate it!
