### ISSUE TITLE
Team not restored after going AFK

### ISSUE THREAD

**Issue by Deeptanil** [clo4/datapacks#31]
After going afk and changing team to afk it doesnt change back to red (indicator that they are the tagger).
https://modrinth.com/datapack/tag-game

**Comment by clo4** [comment]
Yeah... figured this might happen eventually 😅 I experimented with this a while ago but decided it wasn't worth it, since at the time it was a hypothetical problem and it added a lot of complexity to what was, at that point, an *example* data pack.

This is worth the time to look into it since there's now a few hundred people using this. I'll mull it over and see if I can come up with something :)

**Comment by Deeptanil** [comment]
Yes 😆 it could be fixed by just integrated/working with the other devs. Heres the other issue on their git: https://github.com/SuperDyl/tag-game/issues/1

**Comment by clo4** [comment]
Released a version with this fixed! https://modrinth.com/datapack/afk-dim-names/version/YSllOPtW

**Comment by SuperDyl** [comment]
@clo4 , if you didn't see the issue on my project, I have resolved the problem on my end as well. My tag game datapack now officially supports your AFK tag

**Comment by clo4** [comment]
@SuperDyl Had a look, I like your solution. Both of our data packs are less likely to break and be broken 👍👍

And also @Deeptanil, thanks for bringing this up - pretty neat that it turned out to be actionable for both of us.
